void I2C_EV_IRQHandling(I2C_Handle_t *pI2CHandle)
{
	//Interrupt handling for both Master and Slave mode of a device

	//[1] SB :  Handle For interrupt generated by SB event
	//	  Note : SB flag is only applicable in Master mode

	//[2] ADDRF: Handle For interrupt generated by ADDR event
	//	  Note : When master mode : Address is sent

	//[3] BTF: Handle For interrupt generated by BTF(Byte Transfer Finished) event

	//[4] STOPF: Handle For interrupt generated by STOPF event

	//[5] TXE: Handle For interrupt generated by TXE event
	
	//[6] RXNE Handle For interrupt generated by RXNE event
}